name: CI run

on:
  pull_request:
    branches: [ "develop" ]

  # To allow the workflow to run manyally from the actions tab in github repository
  workflow_dispatch:


jobs:
  android:
    # Choosing type of runner for this job
    runs-on: ubuntu-latest

    steps:
      # Reads repository under $GITHUB_WORKSPACE so job can access it
      - uses: actions/checkout@v4
      # install java sdk
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"
          # cache java sdk for faster future runs
          cache: 'gradle'

      - name: Setup Android SDK
        uses: amyu/setup-android@v4
        with:
          # default: 34
          # It will always be installed.
          sdk-version: 34
          # default: 33.0.2
          # build tools version
          # see https://developer.android.com/studio/releases/build-tools
          # It will always be installed.
          build-tools-version: 33.0.2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      # install flutter sdk
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3"
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test

      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build appbundle
